name: CI

on:
  push:
    branches:
      - master
      - release-*
  pull_request:

jobs:
  build-unix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        java_version_build:
          - 11
          - 14
        java_version_test:
          -  7
#          -  8
#          -  9
#          - 10
#          - 11
#          - 12
#          - 13
          - 14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java for build
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version_build }}
      - name: Print environment for debugging
        run: env
      - name: Build
        run: ./gradlew -PallTests build
      - name: Prepare integration test
        run: ./gradlew publishToMavenLocal
      - name: Set up Java for integration test
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version_test }}
      - name: Print environment for debugging
        run: env
      - name: Integration test
        env:
          JAVA_VERSION_BUILD: ${{ matrix.java_version_build }}
          JAVA_VERSION_TEST: ${{ matrix.java_version_test }}
        run: |
          echo ${JAVA_VERSION_TEST}
          JAVA_HOME_MAVEN=${JAVA_HOME}
          echo ${JAVA_HOME_MAVEN}

          echo ${JAVA_VERSION_BUILD}
          JAVA_HOME_BUILD_TEMPLATE=JAVA_HOME_${JAVA_VERSION_BUILD}_X64
          echo ${JAVA_HOME_BUILD_TEMPLATE}
          JAVA_HOME=${!JAVA_HOME_BUILD_TEMPLATE}
          echo ${JAVA_HOME}
          echo "./gradlew runMavenTest -Pjava${JAVA_VERSION_TEST}Home=${JAVA_HOME_MAVEN}"
          ./gradlew runMavenTest -Pjava${JAVA_VERSION_TEST}Home=${JAVA_HOME_MAVEN}
  build-windows:
    strategy:
      matrix:
        os:
          - windows-latest
        java_version_build:
          - 11
          - 14
        java_version_test:
          -  7
#          -  8
#          -  9
#          - 10
#          - 11
#          - 12
#          - 13
          - 14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java for build
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version_build }}
      - name: Print environment for debugging
        run: env
      - name: Build
        run: .\gradlew.bat -PallTests build
      - name: Prepare integration test
        run: .\gradlew.bat publishToMavenLocal
      - name: Set up Java for integration test
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version_test }}
      - name: Print environment for debugging
        run: env
      - name: Integration test
        env:
          JAVA_VERSION: ${{ matrix.java_version_test }}
        run: |
          $env:JAVA_VERSION
          $env:JAVA_VERSION
          $env:JAVA_HOME_MAVEN = $env:JAVA_HOME
          $env:JAVA_HOME_MAVEN
          $env:JAVA_HOME_TEMPLATE = "JAVA_HOME_$($env:JAVA_VERSION)_X64"
          $env:JAVA_HOME_TEMPLATE
          $env:JAVA_HOME = $env:JAVA_HOME_TEMPLATE
          $env:JAVA_HOME
          .\gradlew.bat runMavenTest "-Pjava$($env:JAVA_VERSION)Home=$($env:JAVA_HOME_MAVEN)"

# TODO: Push to internal Github Registry
