name: CI

on:
  push:
    branches:
      - master
      - release-*
  pull_request:

jobs:
  build-unix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        java_version:
          -  7
          -  8
          -  9
          - 10
          - 11
          - 12
          - 13
          - 14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java for build
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew -PallTests build
      - name: Prepare integration test
        run: ./gradlew publishToMavenLocal
      - name: Set up Java for integration test
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Integration test
        run: |
          JAVA_HOME_MAVEN=${JAVA_HOME}
          echo ${JAVA_HOME_MAVEN}
          JAVA_HOME=${JAVA_HOME_11_X64} &&
          echo ${JAVA_HOME}
          ./gradlew runMavenTest
  build-windows:
    strategy:
      matrix:
        os:
          - windows-latest
        java_version:
          -  7
          -  8
          -  9
          - 10
          - 11
          - 12
          - 13
          - 14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java for build
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: .\gradlew.bat -PallTests build
      - name: Prepare integration test
        run: .\gradlew.bat publishToMavenLocal
      - name: Set up Java for integration test
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Integration test
        run: |
          $env:JAVA_HOME_MAVEN = $env:JAVA_HOME
          $env:JAVA_HOME_MAVEN
          $env:JAVA_HOME = $env:JAVA_HOME_11_X64
          $env:JAVA_HOME
          .\gradlew.bat runMavenTest
